
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analyzers;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int espacioTab = 21;
  public static final int procedimiento = 20;
  public static final int constant = 17;
  public static final int identifier = 4;
  public static final int coma = 9;
  public static final int parentesisAbierto = 10;
  public static final int cabecera = 2;
  public static final int punto = 6;
  public static final int inicio = 16;
  public static final int igual = 3;
  public static final int real = 15;
  public static final int EOF = 0;
  public static final int parentesisCerrado = 11;
  public static final int error = 1;
  public static final int constanteReal = 14;
  public static final int entero = 18;
  public static final int fin = 12;
  public static final int dosPuntos = 8;
  public static final int var = 13;
  public static final int puntoComa = 7;
  public static final int funcion = 19;
  public static final int constanteEntera = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "cabecera",
  "igual",
  "identifier",
  "constanteEntera",
  "punto",
  "puntoComa",
  "dosPuntos",
  "coma",
  "parentesisAbierto",
  "parentesisCerrado",
  "fin",
  "var",
  "constanteReal",
  "real",
  "inicio",
  "constant",
  "entero",
  "funcion",
  "procedimiento",
  "espacioTab"
  };
}

