
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analyzers;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int condMayor = 27;
  public static final int suma = 22;
  public static final int parentesisCerrado = 11;
  public static final int resta = 23;
  public static final int repite = 37;
  public static final int dosPuntos = 8;
  public static final int condY = 44;
  public static final int hasta = 38;
  public static final int coma = 9;
  public static final int entonces = 34;
  public static final int igual = 3;
  public static final int condO = 43;
  public static final int identifier = 4;
  public static final int inicio = 16;
  public static final int procedimiento = 20;
  public static final int constanteString = 45;
  public static final int real = 15;
  public static final int si = 32;
  public static final int mientras = 35;
  public static final int parentesisAbierto = 10;
  public static final int var = 13;
  public static final int EOF = 0;
  public static final int producto = 24;
  public static final int para = 39;
  public static final int error = 1;
  public static final int entero = 18;
  public static final int negacion = 31;
  public static final int constant = 17;
  public static final int punto = 6;
  public static final int funcion = 19;
  public static final int cabecera = 2;
  public static final int condMenorIgual = 29;
  public static final int puntoComa = 7;
  public static final int hastaAbajo = 41;
  public static final int hacer = 36;
  public static final int fin = 12;
  public static final int constanteEntera = 5;
  public static final int constanteReal = 14;
  public static final int condMayorIgual = 30;
  public static final int paquete = 42;
  public static final int hastaArriba = 40;
  public static final int division = 25;
  public static final int asignacion = 21;
  public static final int modulo = 26;
  public static final int condMenor = 28;
  public static final int sino = 33;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "cabecera",
  "igual",
  "identifier",
  "constanteEntera",
  "punto",
  "puntoComa",
  "dosPuntos",
  "coma",
  "parentesisAbierto",
  "parentesisCerrado",
  "fin",
  "var",
  "constanteReal",
  "real",
  "inicio",
  "constant",
  "entero",
  "funcion",
  "procedimiento",
  "asignacion",
  "suma",
  "resta",
  "producto",
  "division",
  "modulo",
  "condMayor",
  "condMenor",
  "condMenorIgual",
  "condMayorIgual",
  "negacion",
  "si",
  "sino",
  "entonces",
  "mientras",
  "hacer",
  "repite",
  "hasta",
  "para",
  "hastaArriba",
  "hastaAbajo",
  "paquete",
  "condO",
  "condY",
  "constanteString"
  };
}

