
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int op_mas = 15;
  public static final int op_mayor_igual = 5;
  public static final int p_else = 9;
  public static final int p_do = 11;
  public static final int op_igual_doble = 21;
  public static final int corchete_cerrado = 25;
  public static final int op_igual = 14;
  public static final int op_and_doble = 7;
  public static final int coma = 26;
  public static final int parentesis_cerrado = 23;
  public static final int punto_y_coma = 27;
  public static final int constfloat = 35;
  public static final int op_menor_igual = 4;
  public static final int real = 29;
  public static final int op_menos = 16;
  public static final int op_not = 20;
  public static final int op_menor = 2;
  public static final int p_buclefor = 13;
  public static final int EOF = 0;
  public static final int ident = 33;
  public static final int error = 1;
  public static final int op_div = 18;
  public static final int op_mayor = 3;
  public static final int entero = 28;
  public static final int corchete_abierto = 24;
  public static final int parentesis_abierto = 22;
  public static final int p_until = 12;
  public static final int p_if = 8;
  public static final int constint = 34;
  public static final int p_define = 30;
  public static final int op_mod = 19;
  public static final int op_or_doble = 6;
  public static final int p_v = 31;
  public static final int op_mult = 17;
  public static final int p_return = 32;
  public static final int constlit = 36;
  public static final int p_while = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "op_menor",
  "op_mayor",
  "op_menor_igual",
  "op_mayor_igual",
  "op_or_doble",
  "op_and_doble",
  "p_if",
  "p_else",
  "p_while",
  "p_do",
  "p_until",
  "p_buclefor",
  "op_igual",
  "op_mas",
  "op_menos",
  "op_mult",
  "op_div",
  "op_mod",
  "op_not",
  "op_igual_doble",
  "parentesis_abierto",
  "parentesis_cerrado",
  "corchete_abierto",
  "corchete_cerrado",
  "coma",
  "punto_y_coma",
  "entero",
  "real",
  "p_define",
  "p_v",
  "p_return",
  "ident",
  "constint",
  "constfloat",
  "constlit"
  };
}

